include_guard(GLOBAL)

set(DUSKLIGHT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/dusklight"
        CACHE PATH "Path to the Dusklight source tree")
set(DUSKLIGHT_REPOSITORY "https://github.com/TwilitRealm/dusklight.git"
        CACHE STRING "Dusklight git repository to fetch from")

function(_exec_git)
    list(JOIN ARGN " " _args_text)
    execute_process(COMMAND "${GIT_EXECUTABLE}" ${ARGN}
            WORKING_DIRECTORY "${DUSKLIGHT_DIR}"
            RESULT_VARIABLE _result)
    if (NOT _result EQUAL 0)
        message(FATAL_ERROR "'git ${_args_text}' failed.")
    endif ()
endfunction()

set(_dusklight_stamp "${DUSKLIGHT_DIR}/.stamp")
if (EXISTS "${DUSKLIGHT_DIR}/sdk/CMakeLists.txt" AND NOT EXISTS "${_dusklight_stamp}")
    message(STATUS "Dusklight: using existing checkout at ${DUSKLIGHT_DIR}")
else ()
    if (NOT DUSKLIGHT_VERSION)
        message(FATAL_ERROR "Dusklight: DUSKLIGHT_VERSION is not set")
    endif ()
    set(_dusklight_fetched "")
    if (EXISTS "${_dusklight_stamp}")
        file(READ "${_dusklight_stamp}" _dusklight_fetched)
        string(STRIP "${_dusklight_fetched}" _dusklight_fetched)
    endif ()
    if (NOT _dusklight_fetched STREQUAL DUSKLIGHT_VERSION)
        find_package(Git QUIET REQUIRED)
        file(MAKE_DIRECTORY "${DUSKLIGHT_DIR}")
        if (NOT EXISTS "${DUSKLIGHT_DIR}/.git")
            _exec_git(init --quiet)
            _exec_git(remote add origin "${DUSKLIGHT_REPOSITORY}")
        endif ()
        _exec_git(fetch --depth 1 "${DUSKLIGHT_REPOSITORY}" "${DUSKLIGHT_VERSION}")
        _exec_git(-c advice.detachedHead=false checkout --force FETCH_HEAD)
        _exec_git(submodule update --init --depth 1 extern/aurora)
        file(WRITE "${_dusklight_stamp}" "${DUSKLIGHT_VERSION}\n")
    endif ()
endif ()
